language: php
php: 7.4
services: postgresql
before_script:
  - psql -c 'CREATE DATABASE self_control_diary;' -U postgres
  - psql -c "CREATE USER test_user with encrypted password 'test_user_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE self_control_diary TO test_user;" -U postgres

install:
  - composer install
  - php bin/console doctrine:migrations:migrate --allow-no-migration -n -q
  - touch /opt/app/.env.test

script:
  - vendor/bin/codecept run
  - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no
