version: '3'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: self-control-diary
      POSTGRES_PASSWORD: self-control-diary
      POSTGRES_DB: self-control-diary
    ports:
    - 5443:5432

  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: self-control-diary
      MYSQL_USER: self-control-diary
      MYSQL_PASSWORD: self-control-diary
    ports:
      - 3366:3306
