version: '3'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: self-control-diary
      POSTGRES_PASSWORD: self-control-diary
      POSTGRES_DB: self-control-diary
    ports:
    - 5443:5432

  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: self-control-diary
      MYSQL_USER: self-control-diary
      MYSQL_PASSWORD: self-control-diary
    ports:
      - 3366:3306

  php-fpm:
    build: ./deploy
    restart: always
    volumes:
      - .:/var/www:cached
    links:
      - postgres
      - mysql

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./deploy/nginx-hosts:/etc/nginx/conf.d/
      - .:/var/www:cached
    ports:
      - 8080:80
    links:
      - php-fpm
