services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: self-control-diary
      POSTGRES_PASSWORD: self-control-diary
      POSTGRES_DB: self-control-diary
    ports:
      - 5443:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U self-control-diary"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: self-control-diary
      MYSQL_USER: self-control-diary
      MYSQL_PASSWORD: self-control-diary
    ports:
      - 3366:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u self-control-diary --password=self-control-diary"]
      interval: 5s
      timeout: 5s
      retries: 10

  php-fpm:
    build: ./deploy
    restart: always
    volumes:
      - .:/var/www:cached
    links:
      - postgres
      - mysql

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./deploy/nginx-hosts:/etc/nginx/conf.d/
      - .:/var/www:cached
    ports:
      - 8080:80
    links:
      - php-fpm
