#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login:
  path: /api/login
  methods: POST

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
  methods: POST
