name: CI
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    container: php:8.0
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Create database
        run: psql -h postgres -d postgres -U postgres -c "CREATE DATABASE self_control_diary;"
        env:
          PGPASSWORD: postgres
      - name: Check out
        uses: actions/checkout@v4
      - name: Composer
        run: |
          composer install
      - name: Code Style Check
        run: |
          vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no
      - name: Migrations
        env:
          DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/self_control_diary?serverVersion=9&charset=utf8"
          APP_ENV: test
        run: |
          php bin/console doctrine:migrations:migrate --allow-no-migration -n -q
      - name: Codeception
        env:
          DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/self_control_diary?serverVersion=9&charset=utf8"
          APP_ENV: test
        run: |
          vendor/bin/codecept run
